---
title: "Final Project - Mass Shooting Section"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 7
)

library(tidyverse)
library(usmap)
library(rvest)
library(plotly)
library(patchwork)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

Load data.

```{r}
gun_violence_data = read_csv("./data/gun_violence_data_2013_2018.csv")
```

Tidy data.

```{r}
gun_v_tidy = 
	gun_violence_data %>% 
	select(date:city_or_county, n_killed, n_injured, latitude, longitude) %>% 
	separate(date, into = c("year", "month", "day"), sep = "-") %>% 
	mutate(n_affected = n_killed + n_injured) %>%
	filter(n_affected > 0) %>% 
	mutate(mass_shooting = ifelse(n_affected >= 4, "Yes", "No"))
```

## Maps

Centered latitude and longitude points for each state.

```{r}
url = "https://inkplant.com/code/state-latitudes-longitudes"

coord_webpage = read_html(url)
```

```{r}
cent_lat_and_long = 
	coord_webpage %>%
  html_nodes(css = "table") %>% 
	 .[[1]] %>% 
  html_table(header = TRUE) %>% 
  as_tibble() %>% 
	janitor::clean_names() %>% 
	filter(state != "Alaska", state != "Hawaii")
```

Bubble map of mass shootings by state.

```{r}
n_shooting_inc = 
	gun_v_tidy %>% 
	filter(mass_shooting == "Yes") %>% 
	group_by(state) %>% 
	summarize(n_incidents = n())

usa_shooting_inc =
	inner_join(n_shooting_inc, cent_lat_and_long, by = "state")

usa = map_data("state")

ggplot() +
	geom_path(data = usa, aes(x = long, y = lat, group = group)) +
	geom_point(data = usa_shooting_inc, aes(x = longitude, y = latitude, size = n_incidents), color = "darkseagreen3") +
	scale_size(range = c(0, 12))
```

Plotly interactive map of shootings by state.

```{r}
gun_v_tidy %>%
	filter(state != "Alaska", state != "Hawaii", longitude < 0) %>% 
	mutate(n_affected_cat = ifelse(n_affected %in% 4:9, "2: 4-9",
													ifelse(n_affected %in% 10:19, "3: 10-19",
													ifelse(n_affected %in% 20:34, "4: 20-34",
													ifelse(n_affected %in% 35:49, "5: 35-49",
													ifelse(n_affected > 50, "6: 50+", "1: 1-3")))))) %>% 
	mutate(city_state = str_c(city_or_county, state, sep = ", ")) %>% 
	mutate(text_label = str_c(city_state, '\n', year,'\nKilled: ', n_killed, '\nInjured: ', n_injured)) %>% 
  plot_ly(x = ~longitude, y = ~latitude, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~n_affected_cat,
  				colors = "Accent",
  				text = ~text_label)
```

## Time trends

```{r}
n_yearly_shootings = 
	gun_v_tidy %>% 
	group_by(year) %>% 
	summarize(count = n()) %>% 
	filter(year != 2013, year != 2018) %>% 
	mutate(year = as.numeric(year))

n_yearly_mass_violence = 
	gun_v_tidy %>% 
	filter(mass_shooting == "Yes") %>% 
	group_by(year) %>% 
	summarize(count = n()) %>% 
	filter(year != 2013, year != 2018) %>% 
	mutate(year = as.numeric(year))
	
shootings = 
	n_yearly_shootings %>% 
  ggplot(aes(x = year, y = count, fill = year)) +
  geom_bar(stat = "identity") +  
	labs(
    title = "Cumulative Number of Gun Violence Incidents per Year",
    x = "Year",
    y = "Count"
  ) 

mass_violence =
	n_yearly_mass_violence %>% 
	ggplot(aes(x = year, y = count, fill = year)) +
  geom_bar(stat = "identity") +
	labs(
    title = "Cumulative Number of Mass Shootings per Year",
    x = "Year",
    y = "Count"
  ) 

shootings / mass_violence
```





