---
title: "Gun Violence Data"
author: 'Zanis Fang, UID: ZF2213'
date: "11/25/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(usmap)
library(tidyverse)
```

### Exploratory analysis, not for formal dataset

```{r}

gun_violence <- read_csv("./data/gun-violence-data_01-2013_03-2018.csv")

state_abb <- state.abb
names(state_abb) <- state.name

gun_violence_tidy <- gun_violence %>% 
	select(date, state, latitude, longitude, n_killed, n_injured) %>% 
	mutate(year = lubridate::year(date)) %>% 
	mutate(state = state_abb[state],
				 state = ifelse(is.na(state), "DC", state)) %>% 
	select(-date)


if (!file.exists("./data/gun_violence_tidy.csv")) {
	write_csv(x = gun_violence_tidy, path = "./data/gun_violence_tidy.csv")
}

```


```{r compare_cdc_gunvio}
library(tidyverse)

# fixed width dataframe

merged_firearm_mortality <-
	read_csv("./data/merged_firearm_mortality.csv") %>%
	select(state_abb, year, crude_rate, deaths, population, law_strength) %>%
	rename(state = state_abb) %>% 
	unite(col = state_year, state, year, sep = "_")

gun_violence <- read_csv("./data/gun_violence_tidy.csv") %>% 
	sample_n(size = 25000)

gun_violence_merged <- read_csv("./data/gun_violence_tidy.csv") %>%
	group_by(state, year) %>%
	summarize(total_killed = n(), total_injured = n()) %>% 
	unite(col = state_year, state, year, sep = "_")

unempl <- read_csv("./data/unempl.csv") %>% 
	unite(col = state_year, state, year, sep = "_")

merged_data <- full_join(x = gun_violence_merged, y = unempl, by = "state_year")
merged_data <- full_join(x = merged_data, y = merged_firearm_mortality, by = "state_year")
merged_data_wide <- merged_data %>% 
	separate(col = state_year, into = c("state", "year"), sep = "_")

merged_data <- merged_data_wide %>% 
	gather(key = type_variable, value = value, total_killed:law_strength) %>% 
	mutate(year = as.numeric(year)) %>% 
	arrange(year)

merged_data_wide %>%
	# filter(total_killed != 0 & deaths != 0) %>% 
	filter(year <= 2016, year >= 2013) %>% 
	ggplot(aes(x = total_killed, y = deaths)) +
	  geom_point() +
	  scale_x_continuous(limits = c(-1, 5000)) +
	  scale_y_continuous(limits = c(-1, 5000)) +
	  geom_abline(slope = 1, intercept = 0) +
	  facet_grid(. ~ year) +
	  labs(
	  	x = "Gun Violence Dataset Total Killed",
	  	y = "CDC Firearm Total Deaths"
	  )


```

```{r eval = FALSE}
gun_2016 <- merged_data_wide %>% 
	filter(year == 2016, complete.cases(.))


gun_2016_lm <- lm(data = gun_2016, crude_rate ~ unemployment_rate + law_strength + population)

library(plotly)

summary(gun_2016_lm)
gun_2016 %>% plot_ly() %>% 
	add_markers(x = ~unemployment_rate, y = ~crude_rate, z = ~law_strength) %>% 
	add_lines(x = ~unemployment_rate, y = fitted(gun_2016_lm), z = ~law_strength)



```

*Comments:*

1. Note that both datasets have 2014 to 2016 data, but CDC dataset has 1999 to 2013 data.
2. For 2014 to 2016, CDC data seems to be a subset of Gun Violence dataset.


### hispanic

```{r eval = FALSE}

add_hispanic <- read_delim("./data/Firearm Mortality_Hispanic.txt", delim = "\t") %>%
	janitor::clean_names() %>% 
	select(-ten_year_age_groups_code, -injury_mechanism_all_other_leading_causes_code, -notes, -hispanic_origin_code, death_cause = injury_mechanism_all_other_leading_causes) %>% 
	mutate(ten_year_age_groups = factor(ten_year_age_groups, levels = c("1-4 years", "5-14 years", "15-24 years", "25-34 years", "35-44 years", "45-54 years", "55-64 years", "65-74 years", "75-84 years", "85+ years")))

renderPlotly({
  age_hispanic <- add_hispanic %>% 
  filter(year == input$year_2) %>% 
	group_by(ten_year_age_groups, hispanic_origin) %>%
	summarize(n_deaths = sum(deaths),
						n_population = sum(population)) %>% 
	mutate(crude_rate = (n_deaths/n_population) * 100000) %>% 
  spread(key = hispanic_origin, value = crude_rate) %>%
  janitor::clean_names() %>% 
  plot_ly(x = ~ten_year_age_groups,
  				y = ~not_hispanic_or_latino,
  				name = "Not Hispanic or Latino",
  				type = "bar") %>% 
  	add_trace(y = ~hispanic_or_latino,
  						name = "Hispanic or Latino") %>% 
  	layout(barmode = "stack",
  				 xaxis = list(title = "Age Groups"),
  				 yaxis = list(title = "Crude Firearm Death Rate")
  				 )

})

```

# ssamatab1 dataset

```{r}

# download the file if not exist
if (!file.exists("./data/ssamatab1.txt")) {
	download.file("https://www.bls.gov/web/metro/ssamatab1.txt",
								destfile = "./data/ssamatab1.txt")
}
	
# get file name
ssamatab1_file <- "./data/ssamatab1.txt"

# get colname rows
ssamatab1_colname <- read_lines(ssamatab1_file, skip = 3, n_max = 1)
# parse column name, words linked by single space, if not, words without space
ssamatab1_colname <-
	str_extract_all(ssamatab1_colname, "([\\S]+[\\s][\\S]+)|[\\S]+") %>%
	unlist()


# fixed width dataframe
ssamatab1 <- read_delim("./data/ssamatab1.txt",
												delim = "[ ]",
												col_names = "raw",
												skip = 5) %>%
	# filtered out footnote
	filter(str_detect(raw, "MT[0-9]+[\\s]")) %>%
	# separate into columns
	separate(raw, into = ssamatab1_colname, sep = "[\\s]{2,}") %>% 
	# clean column names
	janitor::clean_names() %>%
	rename(fips = code_2) %>% 
	separate(area, into = c("county", "state_source"), sep = ",") %>%
	separate(county,
					 into = paste("county", 1:4, sep = "_"),
					 sep = "-+") %>%
	separate(state_source,
					 into = c("unknown", "state", "source1", "source2"),
					 sep = " ") %>% 
	select(-c("unknown", "source1", "source2")) %>% 
	mutate(rate = as.numeric(rate),
				 fips = as.numeric(fips),
				 year = as.numeric(year)) %>% 
	mutate(employment = as.numeric(str_remove(employment, ","))) %>% 
	mutate(unemployment = as.numeric(str_remove(unemployment, ","))) %>%
	group_by(state, year) %>%
	summarize(unemployment_rate = sum(unemployment) / sum(unemployment * 100 / rate),
						total_unemployment = sum(unemployment)) %>%
	filter(str_length(state) != 2) %>% View
	gather(key = "type_variable", value = "value", unemployment_rate:total_unemployment)

# write_csv(path = "./data/tidy_ssamatab1.csv", x = ssamatab1)




	
usmap::plot_usmap(data = data.frame(
	ssamatab1 %>%
		filter(year == "2016", month == "01") %>% 
		select(state, rate)),
	values = "rate") +
	scale_fill_continuous(low = "white", high = "red")


# take a look at unemployment rate of New York-Newark_Jersey area
ssamatab1 %>%
	filter(state == "NY") %>%
	group_by(fips, year) %>%
	summarize(mean_rate = mean(rate)) %>%
  ggplot(aes(y = mean_rate, x = year, group = fips, color = fips)) +
	  geom_point(show.legend = FALSE) +
	  geom_line(show.legend = FALSE) +
	  labs(
	    title = "Mean unemployment rate for each area",
	    x = "Year",
	    y = "Mean Unemployment rate",
	    color = "Area"
	  ) +
	  theme(
	  	axis.text.x = element_text(angle = 60)
	  )

```


### Try plotly

```{r}
library(plotly)
	
geo1 <- list(
	scope = "usa",
	projection = list(type = "state"),
	showlakes = TRUE,
	lakecolor = toRGB("white")
)

g2 <- list(
	scope = "usa",
	projection = list(type = "state"),
	showlakes = TRUE,
	lakecolor = toRGB("white")
)

plot_geo(ssamatab1, locationmode = "USA-states") %>% 
	add_trace(
		z = ~state_unemployment,
		locations = ~state,
		color = ~state_unemployment,
		colors = "Reds") %>%
	add_markers(
		y = 12,
		x = 12,
		locations = ~state,
		size = ~unemployment,
		colors = "Blues",
		geo = "geo2"
	) %>%
	layout(
		geo = geo1, geo2 = g2
	)

```
```


