---
title: "Gun Violence Data"
author: 'Zanis Fang, UID: ZF2213'
date: "11/25/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Exploratory analysis, not for formal dataset

```{r}

library(tidyverse)
gun_violence <- read_csv("./zanis_dataset/gun-violence-data_01-2013_03-2018.csv")

state_abb <- state.abb
names(state_abb) <- state.name

gun_violence_tidy <- gun_violence %>% 
	select(date, state, latitude, longitude, n_killed, n_injured) %>% 
	mutate(year = lubridate::year(date)) %>% 
	mutate(state = state_abb[state],
				 state = ifelse(is.na(state), "DC", state)) %>% 
	select(-date)
	
# write_csv(x = gun_violence_tidy, path = "./shiny_dataset/gun_violence_tidy.csv")

```


```{r compare_cdc_gunvio}
library(tidyverse)

# fixed width dataframe

merged_firearm_mortality <-
	read_csv("./zanis_dataset/merged_firearm_mortality.csv") %>%
	select(state_abb, year, crude_rate, deaths, population, law_strength) %>%
	rename(state = state_abb) %>% 
	unite(col = state_year, state, year, sep = "_")

gun_violence <- read_csv("./zanis_dataset/gun_violence_tidy.csv") %>% 
	sample_n(size = 25000)

gun_violence_merged <- read_csv("./zanis_dataset/gun_violence_tidy.csv") %>%
	group_by(state, year) %>%
	summarize(total_killed = n(), total_injured = n()) %>% 
	unite(col = state_year, state, year, sep = "_")

unempl <- read_csv("./zanis_dataset/unempl.csv") %>% 
	unite(col = state_year, state, year, sep = "_")

merged_data <- full_join(x = gun_violence_merged, y = unempl, by = "state_year")
merged_data <- full_join(x = merged_data, y = merged_firearm_mortality, by = "state_year")
merged_data_wide <- merged_data %>% 
	separate(col = state_year, into = c("state", "year"), sep = "_")

merged_data <- merged_data_wide %>% 
	gather(key = type_variable, value = value, total_killed:law_strength) %>% 
	mutate(year = as.numeric(year)) %>% 
	arrange(year)

merged_data_wide %>%
	# filter(total_killed != 0 & deaths != 0) %>% 
	filter(year <= 2016, year >= 2013) %>% 
	ggplot(aes(x = total_killed, y = deaths)) +
	  geom_point() +
	  scale_x_continuous(limits = c(-1, 5000)) +
	  scale_y_continuous(limits = c(-1, 5000)) +
	  geom_abline(slope = 1, intercept = 0) +
	  facet_grid(. ~ year) +
	  labs(
	  	x = "Gun Violence Dataset Total Killed",
	  	y = "CDC Firearm Total Deaths"
	  )

gun_2016 <- merged_data_wide %>% 
	filter(year == 2016, complete.cases(.))


gun_2016_lm <- lm(data = gun_2016, crude_rate ~ unemployment_rate + law_strength + population)

library(plotly)

summary(gun_2016_lm)
gun_2016 %>% plot_ly() %>% 
	add_markers(x = ~unemployment_rate, y = ~crude_rate, z = ~law_strength) %>% 
	add_lines(x = ~unemployment_rate, y = fitted(gun_2016_lm), z = ~law_strength)



```

*Comments:*

1. Note that both datasets have 2014 to 2016 data, but CDC dataset has 1999 to 2013 data.
2. For 2014 to 2016, CDC data seems to be a subset of Gun Violence dataset.


### hispanic

```{r}
add_hispanic <- read_delim("./data/Firearm Mortality_Hispanic.txt", delim = "\t") %>% janitor::clean_names()
```

