---
title: "Gun Violence"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(tidyverse)


# for us map
merged_firearm_mortality <-
	read_csv("./zanis_dataset/merged_firearm_mortality.csv") %>%
	select(state_abb, year, crude_rate, deaths, population, law_strength) %>%
	rename(state = state_abb) %>% 
	unite(col = state_year, state, year, sep = "_")

unempl <- read_csv("./zanis_dataset/unempl.csv") %>% 
	unite(col = state_year, state, year, sep = "_")

cdi <- read_csv("./zanis_dataset/sel_cdi.csv") %>% 
	unite(col = state_year, state, year, sep = "_")

merged_data <- full_join(x = cdi, y = unempl, by = "state_year")
merged_data <- full_join(x = merged_data, y = merged_firearm_mortality, by = "state_year") %>%
	separate(col = state_year, into = c("state", "year"), sep = "_") %>%
	gather(key = type_variable, value = Statistics, smoking:law_strength) %>% 
	mutate(year = as.numeric(year), Statistics = round(Statistics, 3)) %>% 
	arrange(year) %>%
	filter(!is.na(Statistics)) %>%
	mutate(type_variable = recode(type_variable,
																unemployment_rate = "Unemployment Rate",
																crude_rate = "Crude Rate",
																deaths = "Deaths",
																population = "Population",
																law_strength = "Law Strength (2016 only)",
																smoking = "Smoking",
																disability_65 = "Disability",
																self_rated_health = "Self Reported Health",
																drinking = "Drinking",
																leisure_phys_act = "Leisure Physical Activities",
																overweight = "Overweight",
																diabetes = "Diabetes",
																mental_health = "Mental Health",
																sleep = "Sleep"))
	
# write_csv(merged_data, "./zanis_dataset/merged_data.csv")

# for barplot
firearm_mortality = read_csv("./devon_data/cdc_firearm_mortality_data.csv", na = "Unreliable") %>% 
	janitor::clean_names() %>% 
	select(-ten_year_age_groups_code, -injury_mechanism_all_other_leading_causes_code, -race_code, death_cause = injury_mechanism_all_other_leading_causes) %>% 
	mutate(ten_year_age_groups = factor(ten_year_age_groups, levels = c("1-4 years", "5-14 years", "15-24 years", "25-34 years", "35-44 years", "45-54 years", "55-64 years", "65-74 years", "75-84 years", "85+ years")))

add_hispanic <- read_delim("./data/Firearm Mortality_Hispanic.txt", delim = "\t") %>%
	janitor::clean_names() %>% 
	select(-ten_year_age_groups_code, -injury_mechanism_all_other_leading_causes_code, -notes, -hispanic_origin_code, death_cause = injury_mechanism_all_other_leading_causes) %>% 
	mutate(ten_year_age_groups = factor(ten_year_age_groups, levels = c("1-4 years", "5-14 years", "15-24 years", "25-34 years", "35-44 years", "45-54 years", "55-64 years", "65-74 years", "75-84 years", "85+ years")))


```

Page 1
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------


```{r}

type_variable <- (merged_data %>% distinct(type_variable) %>% pull())
year <- c(2000:2016)

selectInput("year_1", label = h3("Choose year"),
						choices = as.list(year),
						selected = 2015)

selectInput("variable_type", label = h3("Choose variable"),
						choices = type_variable, selected = "Law Strength (2016 only)")

```

Column
-----------------------------------------------------------------------

### US MAP

```{r}
# for text
state_abb <- state.name
names(state_abb) <- state.abb

# plot_geo
renderPlotly({
	geo1 <- list(
	scope = "usa",
	projection = list(type = "state"),
	showlakes = TRUE,
	lakecolor = toRGB("white")
	)
	
	merged_data %>% 
	filter(type_variable == input$variable_type, year == input$year_1) %>% 
	plot_geo(locationmode = "USA-states") %>% 
	add_trace(
		z = ~Statistics,
		locations = ~state,
		color = ~Statistics,
		colors = "Reds",
		text = ~paste(type_variable, state_abb[state], sep = "<br />")
		) %>%
	layout(
		geo = geo1,
		title = "US Map - State Statistics",
		legend = list(x = 100, y = 0.5)
	)
})



# rsconnect::deployApp("./shiny_states.Rmd")

```

Page 2
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput("year_2", label = h3("Choose year"),
						choices = as.list(year), selected = 2013)
```



Row
-----------------------------------------------------------------------

### Crude Firearm Death Rate Across All States by Age Group and Race

```{r}

renderPlotly({
  age_race <- firearm_mortality %>% 
  filter(year == input$year_2) %>% 
	group_by(ten_year_age_groups, race) %>%
	summarize(n_deaths = sum(deaths),
						n_population = sum(population)) %>% 
	mutate(crude_rate = (n_deaths/n_population) * 100000) %>% 
  spread(key = race, value = crude_rate) %>%
  janitor::clean_names() %>% 
  plot_ly(x = ~ten_year_age_groups,
  				y = ~white,
  				name = "White",
  				type = "bar") %>% 
  	add_trace(y = ~american_indian_or_alaska_native,
  						name = "American Indian or Alaska Native") %>% 
  	add_trace(y = ~asian_or_pacific_islander,
  						name = "Asian or Pacific Islander") %>% 
  	add_trace(y = ~american_indian_or_alaska_native,
  						name = "American Indian or Alaska Native") %>% 
  	layout(barmode = "stack",
  				 xaxis = list(title = "Age Groups"),
  				 yaxis = list(title = "Crude Firearm Death Rate")
  				 )

})

```

Row
-----------------------------------------------------------------------

### Crude Firearm Death Rate Across All States by Age Group and Hispanic Origin

```{r}
renderPlotly({
  age_hispanic <- add_hispanic %>% 
  filter(year == input$year_2) %>% 
	group_by(ten_year_age_groups, hispanic_origin) %>%
	summarize(n_deaths = sum(deaths),
						n_population = sum(population)) %>% 
	mutate(crude_rate = (n_deaths/n_population) * 100000) %>% 
  spread(key = hispanic_origin, value = crude_rate) %>%
  janitor::clean_names() %>% 
  plot_ly(x = ~ten_year_age_groups,
  				y = ~not_hispanic_or_latino,
  				name = "Not Hispanic or Latino",
  				type = "bar") %>% 
  	add_trace(y = ~hispanic_or_latino,
  						name = "Hispanic or Latino") %>% 
  	layout(barmode = "stack",
  				 xaxis = list(title = "Age Groups"),
  				 yaxis = list(title = "Crude Firearm Death Rate")
  				 )

})


```



Row
-----------------------------------------------------------------------

### Description

(Fill description here)


