---
title: "Socioeconomic status"
author: 'Zanis Fang, UID: ZF2213'
date: "11/14/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(usmap)
library(rsconnect)

```


```{r}
# download the file if not exist
if (!file.exists("./dataset/ssamatab1.txt")) {
	download.file("https://www.bls.gov/web/metro/ssamatab1.txt",
								destfile = "./dataset/ssamatab1.txt")
}
	
# get file name
ssamatab1_file <- "./dataset/ssamatab1.txt"

# get colname rows
ssamatab1_colname <- read_lines(ssamatab1_file, skip = 3, n_max = 1)
# parse column name, words linked by single space, if not, words without space
ssamatab1_colname <-
	str_extract_all(ssamatab1_colname, "([\\S]+[\\s][\\S]+)|[\\S]+") %>%
	unlist()


# fixed width dataframe
ssamatab1 <- read_delim("./dataset/ssamatab1.txt",
												delim = "[ ]",
												col_names = "raw",
												skip = 5) %>%
	# filtered out footnote
	filter(str_detect(raw, "MT[0-9]+[\\s]")) %>%
	# separate into columns
	separate(raw, into = ssamatab1_colname, sep = "[\\s]{2,}") %>% 
	# clean column names
	janitor::clean_names() %>%
	rename(fips = code_2) %>% 
	separate(area, into = c("county", "state_source"), sep = ",") %>%
	separate(county,
					 into = paste("county", 1:4, sep = "_"),
					 sep = "-+") %>%
	separate(state_source,
					 into = c("unknown", "state", "source1", "source2"),
					 sep = " ") %>% 
	select(-c("unknown", "source1", "source2")) %>% 
	mutate(rate = as.numeric(rate),
				 fips = as.numeric(fips),
				 year = as.numeric(year)) %>% 
	mutate(employment = as.numeric(str_remove(employment, ","))) %>% 
	mutate(unemployment = as.numeric(str_remove(unemployment, ","))) %>%
	group_by(state, year) %>%
	summarize(unemployment_rate = sum(unemployment) / sum(unemployment * 100 / rate),
						total_unemployment = sum(unemployment)) %>%
	filter(str_length(state) != 2) %>% View
	gather(key = "type_variable", value = "value", unemployment_rate:total_unemployment)

# write_csv(path = "./shiny_dataset/tidy_ssamatab1.csv", x = ssamatab1)




	
usmap::plot_usmap(data = data.frame(
	ssamatab1 %>%
		filter(year == "2016", month == "01") %>% 
		select(state, rate)),
	values = "rate") +
	scale_fill_continuous(low = "white", high = "red")


# take a look at unemployment rate of New York-Newark_Jersey area
ssamatab1 %>%
	filter(state == "NY") %>%
	group_by(fips, year) %>%
	summarize(mean_rate = mean(rate)) %>%
  ggplot(aes(y = mean_rate, x = year, group = fips, color = fips)) +
	  geom_point(show.legend = FALSE) +
	  geom_line(show.legend = FALSE) +
	  labs(
	    title = "Mean unemployment rate for each area",
	    x = "Year",
	    y = "Mean Unemployment rate",
	    color = "Area"
	  ) +
	  theme(
	  	axis.text.x = element_text(angle = 60)
	  )

```


### Try plotly

```{r}
library(plotly)
	
geo1 <- list(
	scope = "usa",
	projection = list(type = "state"),
	showlakes = TRUE,
	lakecolor = toRGB("white")
)

g2 <- list(
	scope = "usa",
	projection = list(type = "state"),
	showlakes = TRUE,
	lakecolor = toRGB("white")
)

plot_geo(ssamatab1, locationmode = "USA-states") %>% 
	add_trace(
		z = ~state_unemployment,
		locations = ~state,
		color = ~state_unemployment,
		colors = "Reds") %>%
	add_markers(
		y = 12,
		x = 12,
		locations = ~state,
		size = ~unemployment,
		colors = "Blues",
		geo = "geo2"
	) %>%
	layout(
		geo = geo1, geo2 = g2
	)

```

### unemployment data (State)

https://fred.stlouisfed.org/search?st=unemployment+rate

Unemployment data of 51 states (including District of Columbia) from 1976 to 2018 were downloaded and extracted from FRED economic research website. Tidy dataset was write into a "unempl.csv" file under "/zanis_dataset" folder.

```{r}

unempl_files <-
	tibble(state = list.files("./zanis_dataset/unemployment", full.names = TRUE)) %>%
	mutate(data = map(.x = state, .f = ~read_csv(.x))) %>%
	mutate(state = str_extract(state, "[A-Z]{4}"))

unempl <- unempl_files$data[[1]]
for (i in 2:nrow(unempl_files)) {
	unempl <- full_join(unempl, unempl_files$data[[i]], by = "DATE")
}

unempl <- unempl %>% 
	gather(key = state, value = unemployment_rate, AKUR:WYUR) %>% 
	mutate(state = str_extract(state, "^[A-Z]{2}")) %>%
	mutate(year = lubridate::year(DATE)) %>% 
	group_by(state, year) %>% 
	summarize(unemployment_rate = mean(unemployment_rate))
	
# write_csv(x = unempl, path = "./zanis_dataset/unempl.csv")
```



